### ISSUE TITLE
Segmentation fault on incorrect configuration

### ISSUE THREAD

**Issue by m01** [OpenOverlayRouter/oor#11]
I tried starting the OOR with the following in my config:
```
static-map-cache {
#    eid-prefix          = <ip-prefix/mask>
#    iid                 = 0
#    rloc-address {
#        address         = <string>
#        priority        = <int>
#        weight          = <int>
#    }
}
```

Note the content was commented out rather than the block around it. This resulted in a segfault here (rather than a configuration error): [oor_config_confuse.c:183](https://github.com/OpenOverlayRouter/oor/blob/748758a3312dad0610ac745178bd180e7302351c/oor/config/oor_config_confuse.c#L183)

**Comment by albert-lopez** [comment]
Thanks for reporting us this error. It has been fixed in d661007174f65096543ebe26e56c79d9ec18e296 
This bug fix will be available in the new release of OOR
