### ISSUE TITLE
Provide binary package for Turris Omnia router

### ISSUE THREAD

**Issue by renne** [OpenOverlayRouter/oor#24]
The [Turris Omnia router](https://omnia.turris.cz/en/) uses a modified OpenWRT 15.05. Please provide an OOR-package. I opened an issue [OpenOverlayRouter package](https://github.com/CZ-NIC/turris-os-packages/issues/51) in the [turris-os-packages repository](https://github.com/CZ-NIC/turris-os-packages).

**Comment by albert-lopez** [comment]
I have generated the OOR package for OpenWRT 17.01 (they removed the branch for 15.05). Try if it works. If not, we would try to find a copy of 15.05. You can download the package [here](http://www.openoverlayrouter.org/downloads/OpenWrt/1.2.1/oor_1.2.1-5_marvell_armada_37x_38x_xp.ipk)

**Comment by renne** [comment]
```
root@turris:/tmp/run/mountd/sde1# opkg install ./oor_1.2.1-5_marvell_armada_37x_38x_xp.ipk 
Unknown package 'oor'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for oor found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package oor.
```

I suggest to fork the [turris-os-packages repository](https://github.com/CZ-NIC/turris-os-packages/tree/test/net), add an OOR Makefile and make a pull request.

**Comment by renne** [comment]
@BKPepe from the TurrisOS project [has asked to add the package to the OpenWRT package repository](https://github.com/CZ-NIC/turris-os-packages/issues/51#issuecomment-405377467).

Running a primary nameserver on the Turris Omnia via LISP would be great!

**Comment by renne** [comment]
Push ...

**Comment by renne** [comment]
Duplicate of #34
