### ISSUE TITLE
Add OpenOverlayRouter as community package to OpenWRT repository

### ISSUE THREAD

**Issue by renne** [OpenOverlayRouter/oor#34]
The [OpenWRT community repository](https://github.com/openwrt/packages) provides the outdated LISPmob 4.0.1 (package `lispd`). To provide binary packages for all hardware platforms I suggest to add the current OOR version to the [OpenWRT community repository](https://github.com/openwrt/packages) as a GIT-submodule via fork/pull request.

**Comment by albert-lopez** [comment]
We have done a pull request to the OpenWRT project. We will wait to be the pull request accepted to close this request
