### ISSUE TITLE
help

### ISSUE THREAD

**Issue by caojing1996** [OpenOverlayRouter/oor#37]
i try to run oor from openwrt,but it have some problem. so,i need a example for oor , such as /etc/config/oor 。thanks so much.the troublres are map cache  can add ,no output iface no contol iface .i set control iface eth0。but useless.

**Comment by albert-lopez** [comment]
I added a simple configuration file as an xTR example. The section control_iface is not used for an xTR. The control and data ifaces that OOR will use when it is configured as an xTR are the ones associated with RLOCs. In the configuration file, you have an example of the two ways and RLOC can be defined: rloc-address where you specify directly the initial address that the interface has, or rloc-iface where you indicate the name of the interface. Remember that you should have previously configured the rloc interfaces and eid interfaces.


[oor.conf.example.txt](https://github.com/OpenOverlayRouter/oor/files/2614701/oor.conf.example.txt)

**Comment by caojing1996** [comment]
thank you for your reply ,i add some config and make it run success.before this i try it success in the linux 。Your suggestion is very useful.
