### ISSUE TITLE
Feature request: Make it configurable which traffic is routed via the tunnel device

### ISSUE THREAD

**Issue by v0101** [OpenOverlayRouter/oor#38]
At the moment all traffic is routed via the tunnel device. This is because on startup 2 routes are set:
```
0.0.0.0         0.0.0.0         128.0.0.0       U     0      0        0 lispTun0
128.0.0.0       0.0.0.0         128.0.0.0       U     0      0        0 lispTun0
```
It would be good to have a configuration possibility to route only traffic that has the destination in the lisp network via the lispTun0 device.
At the moment we need to delete the 2 routes and add a new route to send only traffic for the lisp network to the lisp device:
```./oor -f /root/oor/oor.conf -D && sleep 5 && route del -net 0.0.0.0 gw 0.0.0.0 netmask 128.0.0.0; route del -net 128.0.0.0 gw 0.0.0.0 netmask 128.0.0.0; route add -net 192.168.17.0 netmask 255.255.255.0 dev lispTun0```

**Comment by albert-lopez** [comment]
This feature has been added with commit 4818f37020ca9a846cd7881c4b1e51fc2cae3a71 . 
allowed-dst-eids section added in the configuration file. This feature is only available in linux and openWRT distributions
